### ISSUE TITLE
README's assumptions about Terra binary location

### ISSUE THREAD

**Issue by 0joshuaolson1** [terralang/terra#126]
For the Linux release at least,
`$ ./terra tests/hello.t`
should be
`$ bin/terra share/terra/tests/hello.t`
But the file hierarchy is different when building from source, is it not? I think correcting this would either require complicating the readme or using symlinks (which don't work on Windows?).

**Comment by zdevito** [comment]
Yes, they can be updated to refer to the `release` directory. It should
have the same structure whether in the source code or binary distribution
(in the source, the binary directory is just <repository>/release).

**Comment by 0joshuaolson1** [comment]
I admit that I don't understand what you mean. I haven't built from source, so I'm guessing the other version would look like `build/SOMETHING/terra tests/hello.t`?

**Comment by elliottslaughter** [comment]
I think Terra's Makefile has installed a symlink from `release/bin/terra` to `terra` for a long time now.

On the other hand, CMake doesn't work this way, but it's really impossible to know what path to put since the user could install it anywhere. I don't think it's unreasonable to assume the user will know where they installed Terra?

At any rate, I'm closing this unless someone wants to take a look at the modern READE file and give a concrete suggestion for what to change. (As per the original issue title, PR's are great too.)
