### ISSUE TITLE
OpenBSD

### ISSUE THREAD

**Issue by indieterminacy** [terralang/terra#312]
Hi,

Do you have any plans for having a version that works on OpenBSD?

**Comment by elliottslaughter** [comment]
Hi and welcome!

At the moment, Terra is completely volunteer run. We'd love to support as many platforms as possible, but practically speaking we rely on people to come forward and fix stuff when it's broken. So I can't make any promises about OpenBSD unless you're interesting in supporting it yourself. :smiley: 

Having said that, there was a patch a while ago for FreeBSD, so it's possible this would just work out of the box for you:

https://github.com/zdevito/terra/pull/265

Have you tried using Terra on OpenBSD?

**Comment by indieterminacy** [comment]
I had recently discovered your language and am keen to use it to go beyond my lua/luajit coding - Im sold on your philosophy for the project, particularly given that I havent yet invested a large amount of time into C.

At the moment I am converting and parsing a significant volume of data. Conventionally on Linux, I am using an OpenBSD VPS to free up resources on my machine.

Your (prompt!) feedback gives me useful signals re when (rather than if) I delve into Terra. I will will experiment later on a local machine once automation has kicked in with my VPS.

I had a look at the patch and will provide feedback with regards to it should I get the time to experiment.

Ta!

**Comment by elliottslaughter** [comment]
Well I can't take the credit, this is all work done by @zdevito and others. I'm mostly just the guy trying to keep the project alive because I use it myself.

But anyway, that all sounds good and feel free to post here (and/or in a new issue) if anything comes up when you try it out.

If you do have issues, then probably what that indicates is that we should try to find a way to put some sort of *BSD in the CI. I'm not aware of any approaches to do that except possibly Gitlab, which has some pretty serious drawbacks when the primary project is on Github. But maybe there's another, more well-integrated option that I'm not aware of. CI is the main way we keep ourselves sane on this project so it would be good to do this in general.

**Comment by elliottslaughter** [comment]
There hasn't been much activity on this issue, and unfortunately (since we're entirely volunteer based) we can't support a system unless someone steps up to help.

For the moment, I'm going to close this issue, but if someone wants to help support BSD variants, I'm more than happy to do what I can to facilitate such an effort.
