### ISSUE TITLE
Can terra compile down to lua?

### ISSUE THREAD

**Issue by ktalebian** [terralang/terra#356]
I use lua with openresty in my application. Been looking at Terra to allow typed scripting. Is it possible to compile terra code down to lua?

**Comment by capr** [comment]
Terra generates LLVM IR which is then jit-compiled and called through the LuaJIT ffi. Maybe Typed Lua (https://github.com/andremm/typedlua) might be closer to what you want.

**Comment by elliottslaughter** [comment]
I'll just add two other languages that may be interesting in this space:

  * Titan: https://github.com/titan-lang/titan
  * Pallene: https://github.com/pallene-lang/pallene

Since this is fairly different from what Terra provides (and e.g. it's an explicit goal for Terra to generate code that is independent of the Lua interpreter), I'm going to close this issue. But if there are any further questions, let us know.
