### ISSUE TITLE
/usr/include no longer exists on macOS 10.14

### ISSUE THREAD

**Issue by elliottslaughter** [terralang/terra#365]
On macOS 10.14 with an updated copy of the Command Line Tools, `/usr/include` no longer appears to exist. This means that Terra fails to find basic headers like `math.h`. Terra relies on Clang for this functionality, but a generic (non-Apple) Clang build doesn't seem to be smart enough to find it, at least as of LLVM 7.

A short-term workaround for this is to set `INCLUDE_PATH` to the location where headers are located. On my machine this is `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include`.

Hopefully in the longer term LLVM will be updated to be able to find the headers. Otherwise we'll have to find some way of locating them ourselves, and I can't think of any solution that isn't going to be very brittle. For example, running `/usr/bin/clang++ -E -x c - -v < /dev/null` prints the system search path, but I'm not sure we can depend on the output of this command being stable.

**Comment by pmccormick** [comment]
It is not clear how long this will continue to be provided by Apple but there is a fix for this (or at least I think it should work).

Try installing:

  /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14. pkg

(Clear as mud as far as obvious solutions go…)

On Apr 3, 2019, at 9:48 PM, Elliott Slaughter <notifications@github.com<mailto:notifications@github.com>> wrote:


On macOS 10.14 with an updated copy of the Command Line Tools, /usr/include no longer appears to exist. This means that Terra fails to find basic headers like math.h. Terra relies on Clang for this functionality, but a generic (non-Apple) Clang build doesn't seem to be smart enough to find it, at least as of LLVM 7.

A short-term workaround for this is to set INCLUDE_PATH to the location where headers are located. On my machine this is /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1.

Hopefully in the longer term LLVM will be updated to be able to find the headers. Otherwise we'll have to find some way of locating them ourselves, and I can't think of any solution that isn't going to be very brittle. For example, running /usr/bin/clang++ -E -x c++ - -v < /dev/null prints the system search path, but I'm not sure we can depend on the output of this command being stable.

**Comment by elliottslaughter** [comment]
Confirmed that fixes the problem (actually it works better than my workaround). I guess we'll have to revisit this once that package gets removed.

**Comment by elliottslaughter** [comment]
Adding a note to myself to check this again now that #412 has merged. It's possible this problem has finally been fixed.

**Comment by aiverson** [comment]
On nixos global include directories do not exist either. This permits nixos to do things like have multiple major versions of dependencies simultaneously installed for different projects and switch versions around freely, however, it also causes problems when build scripts assume things like "the clang header and library files are this relative path from the LLVM header and library files." Since the build scripts make this assumption and I'm using nixos as my primary OS now (seriously, it's really great) is making my life developing this more difficult.

**Comment by elliottslaughter** [comment]
Let's split nixos off into a separate issue, because macOS still does (as I understand it) have a global location for headers, it's just off in `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr` now instead of `/usr`. In theory the new Clang auto-detect should be smart enough to see that, whereas on nixos I'm guessing the solution will be to either parse the value of `CFLAGS` that the OS gives you, or else to use some sort of scripting to construct the necessary `INCLUDE_PATH`.

**Comment by elliottslaughter** [comment]
I got confirmation today that this has **NOT** been fixed by #412. So I guess Clang's auto-detect isn't smart enough. I do wonder how Apple's Clang manages to get it right though.

**Comment by elliottslaughter** [comment]
This gets even better: in macOS Catalina 10.15, the package mentioned above doesn't exist at all, so there's no way to get `/usr/include` back. The current best guess for a workaround is:

```
export CPATH=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
```

Based on this comment: https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15#comment103258053_58323411

But I sure am not upgrading to find out if it works.

**Comment by elliottslaughter** [comment]
Ok, the `CPATH` fix doesn't seem to work (and in fact, I can't tell what tools even obey `CPATH` in the first place).

Some searching around seems to indicate the solution is to set `SDKROOT`: https://github.com/oracle/truffleruby/issues/1764

**Comment by nateberkopec** [comment]
export SDKROOT=`xcrun --show-sdk-path` works for me.

**Comment by jameshegarty** [comment]
export INCLUDE_PATH=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include

Seemed to fix this for me on Catalina.

**Comment by elliottslaughter** [comment]
I have a branch where I've been playing around with Github Actions, which uses Catalina. The line I've been using there is:

https://github.com/elliottslaughter/terra/blob/github-actions/travis.sh#L148

Though it compiles, the resulting Terra is not fully functional and several tests fail. So there's more debugging to be done here if someone has time/energy to do it.

**Comment by elliottslaughter** [comment]
This isn't fully fixed, but if you follow the set of caveats listed in #435 (namely, setting `-DCMAKE_C_COMPILER=$(which clang)` at configure time and then exporting the environment variable `INCLUDE_PATH="$(xcrun --sdk macosx --show-sdk-path)/usr/include"`) this should now work on both Mojave and Catalina without the need for the header package.

**Comment by elliottslaughter** [comment]
As of #481 Terra now supports `SDKROOT`. If you set that, then it should no longer be necessary to set `INCLUDE_PATH` explicitly.

Since this matches the behavior of Clang itself (see https://github.com/terralang/terra/issues/479#issuecomment-783567086), I'm going to consider this issue fixed.

**Comment by elliottslaughter** [comment]
I confirmed as of #483 the workaround for the setting of `CC` is also no longer necessary. It may have been fixed by `SDKROOT`, or by an unrelated XCode or CLT change, I'm not sure.

So as of this comment, the ONLY setting that is required is `SDKROOT`:

```bash
export SDKROOT="$(xcrun --sdk macosx --show-sdk-path)"
```
